package scanner

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"log"
	"os"
	"strings"
)

// csprojXML is the minimal XML structure of a .csproj file.
// PackageReference elements may appear inside any ItemGroup.
type csprojXML struct {
	ItemGroups []struct {
		PackageRefs []struct {
			Include string `xml:"Include,attr"`
			Version string `xml:"Version,attr"`
		} `xml:"PackageReference"`
	} `xml:"ItemGroup"`
}

// ParseCSProj extracts direct NuGet dependencies from a .csproj MSBuild project file.
// It reads <PackageReference Include="Name" Version="X.Y.Z" /> elements. Returns dependencies
// with Name, Version, [PURL], Ecosystem="nuget", and Direct=true.
func ParseCSProj(path string) ([]Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParseCSProj read %w: %s", err, path)
	}

	var proj csprojXML
	if err := xml.Unmarshal(data, &proj); err != nil {
		return nil, fmt.Errorf("scanner.ParseCSProj parse %w", err)
	}

	var deps []Dependency
	for _, ig := range proj.ItemGroups {
		for _, ref := range ig.PackageRefs {
			if ref.Include == "" {
				continue
			}
			dep := Dependency{
				Name:      ref.Include,
				Version:   strings.TrimLeft(ref.Version, "[]()"),
				Ecosystem: "nuget",
				Direct:    true,
			}
			dep.PURL = BuildPURL("nuget", dep.Name, dep.Version)
			deps = append(deps, dep)
		}
	}

	log.Printf("[INFO] ParseCSProj %s: %d deps", path, len(deps))
	return deps, nil
}

// packagesConfigXML is the XML structure of a packages.config file (legacy NuGet format).
type packagesConfigXML struct {
	Packages []struct {
		ID      string `xml:"id,attr"`
		Version string `xml:"version,attr"`
	} `xml:"package"`
}

// ParsePackagesConfig extracts NuGet dependencies from a packages.config file.
// packages.config is the legacy NuGet format used in .NET Framework projects.
// Returns dependencies with Name, Version, [PURL], Ecosystem="nuget", and Direct=true.
func ParsePackagesConfig(path string) ([]Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParsePackagesConfig read %w: %s", err, path)
	}

	var config packagesConfigXML
	if err := xml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("scanner.ParsePackagesConfig parse %w", err)
	}

	var deps []Dependency
	for _, pkg := range config.Packages {
		if pkg.ID == "" {
			continue
		}
		dep := Dependency{
			Name:      pkg.ID,
			Version:   pkg.Version,
			Ecosystem: "nuget",
			Direct:    true,
		}
		dep.PURL = BuildPURL("nuget", dep.Name, dep.Version)
		deps = append(deps, dep)
	}

	log.Printf("[INFO] ParsePackagesConfig %s: %d deps", path, len(deps))
	return deps, nil
}

// nugetLockEntry represents a single package entry in packages.lock.json.
type nugetLockEntry struct {
	Type        string `json:"type"`
	Resolved    string `json:"resolved"`
	ContentHash string `json:"contentHash"`
}

// ParseNuGetLock extracts the complete dependency graph from a packages.lock.json file.
// The file is generated by NuGet and contains all direct and transitive dependencies,
// each labeled with "type": "Direct" or "Transitive". Returns dependencies with Name,
// Version, [PURL], Ecosystem="nuget", and Direct set per type.
func ParseNuGetLock(path string) ([]Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParseNuGetLock read %w: %s", err, path)
	}

	// Structure: {"version":1, "dependencies":{"net8.0":{"PkgName":{...}}}}
	var raw struct {
		Version      int                                  `json:"version"`
		Dependencies map[string]map[string]nugetLockEntry `json:"dependencies"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("scanner.ParseNuGetLock parse %w", err)
	}

	seen := make(map[string]bool)
	var deps []Dependency

	for _, pkgs := range raw.Dependencies {
		for name, entry := range pkgs {
			if entry.Resolved == "" {
				continue
			}
			key := strings.ToLower(name) + "@" + entry.Resolved
			if seen[key] {
				continue
			}
			seen[key] = true

			dep := Dependency{
				Name:      name,
				Version:   entry.Resolved,
				Ecosystem: "nuget",
				Direct:    strings.EqualFold(entry.Type, "Direct"),
			}
			dep.PURL = BuildPURL("nuget", dep.Name, dep.Version)
			deps = append(deps, dep)
		}
	}

	log.Printf("[INFO] ParseNuGetLock %s: %d deps", path, len(deps))
	return deps, nil
}
