package scanner

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
)

// ParseRequirementsTxt extracts dependencies from a requirements.txt file.
// It handles version specifiers (==, >=, <=, ~=, !=), strips extras, and environment markers.
// Returns dependencies with Name, Version, [PURL], and Ecosystem="pypi".
func ParseRequirementsTxt(path string) ([]Dependency, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParseRequirementsTxt open %w: %s", err, path)
	}
	defer f.Close()

	var deps []Dependency
	sc := bufio.NewScanner(f)

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())

		// Skip comments and options (e.g. -r, --index-url)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "-") {
			continue
		}

		// Strip inline comments
		if idx := strings.Index(line, " #"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}

		// Strip environment markers (semicolon)
		if idx := strings.Index(line, ";"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}

		// Strip extras: package[extra1,extra2]
		if idx := strings.Index(line, "["); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}

		name, version := splitPythonSpec(line)
		if name == "" {
			continue
		}

		dep := Dependency{
			Name:      name,
			Version:   version,
			Ecosystem: "pypi",
			Direct:    true,
		}
		dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
		deps = append(deps, dep)
	}

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scanner.ParseRequirementsTxt scan %w", err)
	}

	log.Printf("[INFO] ParseRequirementsTxt %s: %d deps", path, len(deps))
	return deps, nil
}

// ParsePipfile extracts packages from a Pipfile (TOML-like format).
// It parses [packages] and [dev-packages] sections. Returns dependencies with Name,
// Version, [PURL], and Ecosystem="pypi".
func ParsePipfile(path string) ([]Dependency, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParsePipfile open %w: %s", err, path)
	}
	defer f.Close()

	var deps []Dependency
	inPkgs := false
	sc := bufio.NewScanner(f)

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())

		if idx := strings.Index(line, "#"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}
		if line == "" {
			continue
		}

		lower := strings.ToLower(line)
		if lower == "[packages]" || lower == "[dev-packages]" {
			inPkgs = true
			continue
		}
		if strings.HasPrefix(line, "[") {
			inPkgs = false
			continue
		}

		if !inPkgs {
			continue
		}

		eqIdx := strings.Index(line, "=")
		if eqIdx < 0 {
			continue
		}
		name := strings.TrimSpace(line[:eqIdx])
		rest := strings.Trim(strings.TrimSpace(line[eqIdx+1:]), "\"*")

		version := ""
		if rest != "*" && rest != "" {
			version = strings.TrimLeft(rest, "=~><!^")
		}

		if name == "" {
			continue
		}
		dep := Dependency{
			Name:      name,
			Version:   version,
			Ecosystem: "pypi",
			Direct:    true,
		}
		dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
		deps = append(deps, dep)
	}

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scanner.ParsePipfile scan %w", err)
	}

	log.Printf("[INFO] ParsePipfile %s: %d deps", path, len(deps))
	return deps, nil
}

// splitPythonSpec splits a requirements.txt line like "requests==2.28.0" into name and version.
// It handles ==, >=, <=, ~=, != operators and returns the first version token found, or empty if not pinned.
func splitPythonSpec(spec string) (string, string) {
	// Operators in preference order for version extraction
	operators := []string{"==", "~=", ">=", "<=", "!=", ">", "<"}
	for _, op := range operators {
		if idx := strings.Index(spec, op); idx >= 0 {
			name := strings.TrimSpace(spec[:idx])
			// Take first version constraint value
			rest := strings.TrimSpace(spec[idx+len(op):])
			// If multiple constraints (e.g. ">=1.0,<2.0") take first
			if commaIdx := strings.Index(rest, ","); commaIdx >= 0 {
				rest = rest[:commaIdx]
			}
			return name, strings.TrimSpace(rest)
		}
	}
	// No version specifier - package name only
	return strings.TrimSpace(spec), ""
}

// pipfileLock is the JSON structure of a Pipfile.lock file.
type pipfileLock struct {
	Default map[string]struct {
		Version string `json:"version"`
	} `json:"default"`
	Develop map[string]struct {
		Version string `json:"version"`
	} `json:"develop"`
}

// ParsePipfileLock extracts the complete dependency graph from a Pipfile.lock file.
// Pipfile.lock is generated by Pipenv and contains all resolved transitive dependencies
// with pinned versions in the format "==x.y.z". Returns dependencies with Name, Version,
// [PURL], Ecosystem="pypi", and Direct=false.
func ParsePipfileLock(path string) ([]Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParsePipfileLock read %w: %s", err, path)
	}

	var lock pipfileLock
	if err := json.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("scanner.ParsePipfileLock parse %w", err)
	}

	var deps []Dependency
	for name, pkg := range lock.Default {
		ver := strings.TrimPrefix(pkg.Version, "==")
		dep := Dependency{
			Name:      name,
			Version:   ver,
			Ecosystem: "pypi",
			Direct:    false,
		}
		dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
		deps = append(deps, dep)
	}
	for name, pkg := range lock.Develop {
		ver := strings.TrimPrefix(pkg.Version, "==")
		dep := Dependency{
			Name:      name,
			Version:   ver,
			Ecosystem: "pypi",
			Direct:    false,
		}
		dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
		deps = append(deps, dep)
	}

	log.Printf("[INFO] ParsePipfileLock %s: %d deps", path, len(deps))
	return deps, nil
}

// ParsePoetryLock extracts the complete dependency graph from a poetry.lock or uv.lock file.
// Both formats use a TOML-like structure with [[package]] sections containing "name" and "version" fields.
// The parser handles both formats identically. Returns dependencies with Name, Version, [PURL],
// Ecosystem="pypi", and Direct=false.
func ParsePoetryLock(path string) ([]Dependency, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParsePoetryLock open %w: %s", err, path)
	}
	defer f.Close()

	var deps []Dependency
	var curName, curVer string
	sc := bufio.NewScanner(f)

	flush := func() {
		if curName == "" {
			return
		}
		dep := Dependency{
			Name:      curName,
			Version:   curVer,
			Ecosystem: "pypi",
			Direct:    false,
		}
		dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
		deps = append(deps, dep)
		curName, curVer = "", ""
	}

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())

		if line == "[[package]]" {
			flush()
			continue
		}

		if strings.HasPrefix(line, "name = ") {
			curName = strings.Trim(strings.TrimPrefix(line, "name = "), "\"")
		} else if strings.HasPrefix(line, "version = ") {
			curVer = strings.Trim(strings.TrimPrefix(line, "version = "), "\"")
		}
	}
	flush()

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scanner.ParsePoetryLock scan %w", err)
	}

	log.Printf("[INFO] ParsePoetryLock %s: %d deps", path, len(deps))
	return deps, nil
}

// ParsePyprojectToml extracts direct dependencies from a pyproject.toml file.
// It supports [project] dependencies (PEP 517/518) and [tool.poetry.dependencies] sections.
// Returns dependencies with Name, Version, [PURL], Ecosystem="pypi", and Direct=true.
func ParsePyprojectToml(path string) ([]Dependency, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("scanner.ParsePyprojectToml open %w: %s", err, path)
	}
	defer f.Close()

	var deps []Dependency
	// Track which section we're in
	inProjectDeps := false // [project] dependencies = [...]
	inPoetryDeps := false  // [tool.poetry.dependencies]
	inDepsArray := false   // multi-line array value
	sc := bufio.NewScanner(f)

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())

		// Strip comments
		if idx := strings.Index(line, "#"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}
		if line == "" {
			continue
		}

		// Section headers
		if strings.HasPrefix(line, "[") {
			inProjectDeps = false
			inPoetryDeps = false
			inDepsArray = false
			lower := strings.ToLower(line)
			if lower == "[tool.poetry.dependencies]" {
				inPoetryDeps = true
			}
			continue
		}

		// PEP 517: dependencies = ["requests>=2.28.0", ...]
		if strings.HasPrefix(line, "dependencies") && strings.Contains(line, "=") {
			// Detect if [project] section just started or this is inline
			after := strings.TrimSpace(line[strings.Index(line, "=")+1:])
			if strings.HasPrefix(after, "[") {
				// Could be inline array or start of multi-line
				inProjectDeps = true
				inDepsArray = true
				// Parse inline items
				inner := strings.Trim(after, "[]")
				for _, item := range strings.Split(inner, ",") {
					item = strings.Trim(strings.TrimSpace(item), "\"'")
					name, ver := splitPythonSpec(item)
					if name != "" {
						dep := Dependency{Name: name, Version: ver, Ecosystem: "pypi", Direct: true}
						dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
						deps = append(deps, dep)
					}
				}
				if strings.Contains(after, "]") {
					inDepsArray = false
					inProjectDeps = false
				}
			}
			continue
		}

		// Multi-line array items: "  requests>=2.28.0,"
		if inProjectDeps && inDepsArray {
			if strings.Contains(line, "]") {
				inDepsArray = false
				inProjectDeps = false
			}
			item := strings.Trim(line, "\",]")
			name, ver := splitPythonSpec(item)
			if name != "" {
				dep := Dependency{Name: name, Version: ver, Ecosystem: "pypi", Direct: true}
				dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
				deps = append(deps, dep)
			}
			continue
		}

		// Poetry: name = "^version" or name = {version = "^x.y.z", ...}
		if inPoetryDeps {
			eqIdx := strings.Index(line, "=")
			if eqIdx < 0 {
				continue
			}
			name := strings.TrimSpace(line[:eqIdx])
			if name == "python" {
				continue
			}
			rest := strings.TrimSpace(line[eqIdx+1:])
			ver := ""
			if strings.HasPrefix(rest, "\"") {
				ver = strings.Trim(rest, "\"")
				ver = strings.TrimLeft(ver, "^~>=<!*")
			} else if strings.HasPrefix(rest, "{") {
				ver = extractInlineVersion(rest)
			}
			dep := Dependency{Name: name, Version: ver, Ecosystem: "pypi", Direct: true}
			dep.PURL = BuildPURL("pypi", dep.Name, dep.Version)
			deps = append(deps, dep)
		}
	}

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scanner.ParsePyprojectToml scan %w", err)
	}

	log.Printf("[INFO] ParsePyprojectToml %s: %d deps", path, len(deps))
	return deps, nil
}
